### ISSUE TITLE
Two fixed header rows

### ISSUE THREAD

**Issue by MizunSD** [InQBarna/TableFixHeaders#101]
Hi!
How can I make two top rows fixed? What should I change in TableFixHeaders Class?
Thanks!

**Comment by lorenzos** [comment]
You could just group the layout of the first two cells of each column into a single `View`. This way you will still have a single fixed row, so you can use that library unmodified.

**Comment by MizunSD** [comment]
Thank you, friend!
You saved me a lot of hours
