### ISSUE TITLE
How to pass model array list to MatrixTableAdapter

### ISSUE THREAD

**Issue by aniket-adsul** [InQBarna/TableFixHeaders#124]
How to pass model array list to MatrixTableAdapter

**Comment by mantosh9641** [comment]
Have you done this operation i also need ..
please help me

**Comment by BraisGabin** [comment]
`MatrixTableAdapter` is just an example of how implement a `BaseTableAdapter`. If you don't have a matrix... don't use the matrixAdapter.

But if you want a table you must have, some how, a Matrix structure. Implement that structure using `BaseTableAdapter`

**Comment by mantosh9641** [comment]
One more thing i want to add one more header, for this one what should 
i do ?

**Comment by mantosh9641** [comment]
![untitled](https://user-images.githubusercontent.com/37294497/37384138-28fe06f8-2773-11e8-9e13-2ede4cee0388.png)
Hi can you suggest how can do yellow section with various text .
Thanks

**Comment by mantosh9641** [comment]
hi,BraisGabin i am  waiting  your's answer.
please help me,its urgent .
Thanks 
Mantosh kumar

**Comment by BraisGabin** [comment]
[I'm not](https://github.com/InQBarna/TableFixHeaders/issues/113) [going to](https://github.com/InQBarna/TableFixHeaders/issues/101) [answer that]() [question again.](https://github.com/InQBarna/TableFixHeaders/issues/54) PR welcome :). And don't change the topic of an issue.
