### ISSUE TITLE
Row header above column header in cell -1, -1

### ISSUE THREAD

**Issue by ashx1** [InQBarna/TableFixHeaders#23]
Currently when there is no background set for Cell -1, -1, the column header is above the row header, is it possible to have the row header above the column header when they meet in the first cell (-1, -1)?

Thanks.

**Comment by SaadBilal** [comment]
@ashx1 Can you share your screenshot for review?

**Comment by SaadBilal** [comment]
@ashx1  how you have achieve this behavior, i need your help?

**Comment by ashx1** [comment]
Hi @SaadBilal,
If you want the column to overlap the row then you put the 1st lot of code in the method addTableView in TableFixHeaders.java, if you want the row to overlap the column then you put the 2nd lot of code in the method addTableView in TableFixHeaders.java.

**Comment by SaadBilal** [comment]
@ashx1 Thank you for your reply, i tried that code for row and column but i am unable to achieve required behavior. I have attached two screenshot to show you what is going on and what i want to achieve. Please review that.
Screenshot 1: what is going on currently 
Screenshot 2: what i want to achieve.  (Please Help)
![device-2016-03-31-121342](https://cloud.githubusercontent.com/assets/5398803/14168252/b144d5b6-f73a-11e5-8534-45de6def4368.png)
![screenshot2](https://cloud.githubusercontent.com/assets/5398803/14168257/bb48414c-f73a-11e5-8a60-68cd1327f9ff.png)

**Comment by ashx1** [comment]
@SaadBilal,
Off memory, I think the colour of that cell (-1, -1) has to be transparent as well. I can't look into it until this Sunday, but I think it has to be transparent.

**Comment by SaadBilal** [comment]
@ashx1 I have tried with transparent but unable to achieve. I am waiting for your request and dig deeply into it. Can you share your SKYPE Id?

**Comment by ashx1** [comment]
@SaadBilal I haven't got a Skype Id, if you can wait until this weekend
(hopefully Sunday) I can have a look at what I have done to make it work.

**Comment by SaadBilal** [comment]
@ashx1 Alright :)

**Comment by BraisGabin** [comment]
This is a no supported behavior but you can try to comment this line `canvas.clipRect(widths[0], 0, canvas.getWidth(), canvas.getHeight());` in `drawChild`. That line was added after this issue and it's an optimization to reduce overdraw pixels.

**Comment by SaadBilal** [comment]
Thank you @BraisGabin, I have tried that and now i am close to solution.
