### ISSUE TITLE
How to remove the family view row?

### ISSUE THREAD

**Issue by cchong** [InQBarna/TableFixHeaders#53]
Hi,

I'm having trouble trying to remove the row that returns from getView() under

case 4:
                view = getFamilyView(row, column, convertView, parent);

This is in the FamilyTable.java example and is the row right after the fixed header.  

Thank you.

**Comment by JayeshVarma** [comment]
Hi cchong, I am on same issue can you please elaborate the solution while using getItemViewType

**Comment by cchong** [comment]
Hi Jayesh please take a look at this [link](https://github.com/cchong/TableFixHeaders/compare/cchong-patch-1) to give you an idea of what worked for me.  You may need to change it to suit your needs.

**Comment by JayeshVarma** [comment]
Thank you Christopher, I have one more question, How we handle touch listener on each list item of the table row? I want to change the color and text of (right movable panel).
I have applied onclicklistener to convert view  but it is not working properly. hope you got my question.
thanks!

**Comment by cchong** [comment]
Hi Jayesh, unfortunately it has been a while since I've used the TableFixHeaders library so I am unable to help you with your specific question.  But I imagine you need to play around with the properties to achieve what you're looking for.

**Comment by Masterbee212** [comment]
Hi guys, i need add item onclick in this library. How to make item onclick in tablefixheader. 
 Thanks !

**Comment by BraisGabin** [comment]
Please, no ask things in an issue with a diferent topic. Anyway, before you return a view in you adapter you can set an OnClickListener on the view. Something like: `converView.setOnClickListener(listener);`

**Comment by alasari** [comment]
I tried to use the way on this [link](https://github.com/InQBarna/TableFixHeaders/compare/master...cchong:cchong-patch-1) .but, the application stopped with logchat 

```
java.lang.IndexOutOfBoundsException: Index: 10, Size: 10
at java.util.ArrayList.get(ArrayList.java:411)
at app.al.ti.tianappv3.Dashboard.Feagment.FragmentNilai$NexusTypes.get(FragmentNilai.java:201)
```

I tried to compare my code and i do not find where my mistake, Maybe some one can help me.,.,?

**Comment by rajam1215** [comment]
@alasari 

please use this code with family row

import android.content.Context;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.TextView;

import com.royalways.gnauniversity.R;

import java.util.ArrayList;
import java.util.List;

public class TimeTableAdapter extends BaseTableAdapter {

    private class NexusTypes {

        private final List<Nexus> list;

        NexusTypes() {
            list = new ArrayList<Nexus>();
        }

        private int size() {
            return list.size();
        }

        private Nexus get(int i) {
            return list.get(i);
        }
    }

    private class Nexus {
        private final String[] data;

        private Nexus(String name, String company, String version, String api, String storage, String inches, String ram) {
            data = new String[]{
                    name,
                    company,
                    version,
                    api,
                    storage,
                    inches,
                    ram};
        }
    }

    private Context context;

    private final NexusTypes familys;
    private final String headers[] = {
            "Name",
            "Company",
            "Version",
            "API",
            "Storage",
            "Size",
            "RAM",
    };
    private final int[] widths = {
            120,
            100,
            140,
            60,
            70,
            60,
            60,
    };
    private final float density;

    public TimeTableAdapter(Context context) {
        this.context = context;

        familys = new NexusTypes();

        density = context.getResources().getDisplayMetrics().density;

        familys.list.add(new Nexus("Nexus One", "HTC", "Gingerbread", "10", "512 MB", "3.7\"", "512 MB"));
        familys.list.add(new Nexus("Nexus S", "Samsung", "Gingerbread", "10", "16 GB", "4\"", "512 MB"));
        familys.list.add(new Nexus("Galaxy Nexus (16 GB)", "Samsung", "Ice cream Sandwich", "15", "16 GB", "4.65\"", "1 GB"));
        familys.list.add(new Nexus("Galaxy Nexus (32 GB)", "Samsung", "Ice cream Sandwich", "15", "32 GB", "4.65\"", "1 GB"));
        familys.list.add(new Nexus("Nexus 4 (8 GB)", "LG", "Jelly Bean", "17", "8 GB", "4.7\"", "2 GB"));
        familys.list.add(new Nexus("Nexus 4 (16 GB)", "LG", "Jelly Bean", "17", "16 GB", "4.7\"", "2 GB"));
        familys.list.add(new Nexus("Nexus 7 (16 GB)", "Asus", "Jelly Bean", "16", "16 GB", "7\"", "1 GB"));
        familys.list.add(new Nexus("Nexus 7 (32 GB)", "Asus", "Jelly Bean", "16", "32 GB", "7\"", "1 GB"));
        familys.list.add(new Nexus("Nexus 10 (16 GB)", "Samsung", "Jelly Bean", "17", "16 GB", "10\"", "2 GB"));
        familys.list.add(new Nexus("Nexus 10 (32 GB)", "Samsung", "Jelly Bean", "17", "32 GB", "10\"", "2 GB"));
        familys.list.add(new Nexus("Nexus Q", "--", "Honeycomb", "13", "--", "--", "--"));
    }

    @Override
    public int getRowCount() {
        return familys.size();
    }

    @Override
    public int getColumnCount() {
        return 6;
    }

    @Override
    public View getView(int row, int column, View convertView, ViewGroup parent) {
        final View view;
        switch (getItemViewType(row, column)) {
            case 0:
                view = getFirstHeader(row, column, convertView, parent);
                break;
            case 1:
                view = getHeader(row, column, convertView, parent);
                break;
            case 2:
                view = getFirstBody(row, column, convertView, parent);
                break;
            case 3:
                view = getBody(row, column, convertView, parent);
                break;
            default:
                throw new RuntimeException("wtf?");
        }
        return view;
    }

    private View getFirstHeader(int row, int column, View convertView, ViewGroup parent) {
        if (convertView == null) {
            LayoutInflater inflater = LayoutInflater.from(context);
            convertView = inflater.inflate(R.layout.item_table_header_first, parent, false);
        }
        ((TextView) convertView.findViewById(android.R.id.text1)).setText(headers[0]);
        return convertView;
    }

    private View getHeader(int row, int column, View convertView, ViewGroup parent) {
        if (convertView == null) {
            LayoutInflater inflater = LayoutInflater.from(context);
            convertView = inflater.inflate(R.layout.item_table_header, parent, false);
        }
        ((TextView) convertView.findViewById(android.R.id.text1)).setText(headers[column + 1]);
        return convertView;
    }

    private View getFirstBody(int row, int column, View convertView, ViewGroup parent) {
        if (convertView == null) {
            LayoutInflater inflater = LayoutInflater.from(context);
            convertView = inflater.inflate(R.layout.item_table_first, parent, false);
        }
        convertView.setBackgroundResource(row % 2 == 0 ? R.drawable.bg_table_color1 : R.drawable.bg_table_color2);
        ((TextView) convertView.findViewById(android.R.id.text1)).setText(getDevice(row).data[column + 1]);
        return convertView;
    }

    private View getBody(int row, int column, View convertView, ViewGroup parent) {
        if (convertView == null) {
            LayoutInflater inflater = LayoutInflater.from(context);
            convertView = inflater.inflate(R.layout.item_table, parent, false);
        }
        convertView.setBackgroundResource(row % 2 == 0 ? R.drawable.bg_table_color1 : R.drawable.bg_table_color2);
        ((TextView) convertView.findViewById(android.R.id.text1)).setText(getDevice(row).data[column + 1]);
        return convertView;
    }

    @Override
    public int getWidth(int column) {
        return Math.round(widths[column + 1] * density);
    }

    @Override
    public int getHeight(int row) {
        final int height;
        if (row == -1) {
            height = 35;
        } else {
            height = 45;
        }
        return Math.round(height * density);
    }

    @Override
    public int getItemViewType(int row, int column) {
        final int itemViewType;
        if (row == -1 && column == -1) {
            itemViewType = 0;
        } else if (row == -1) {
            itemViewType = 1;
        } else if (column == -1) {
            itemViewType = 2;
        } else {
            itemViewType = 3;
        }
        return itemViewType;
    }

    private Nexus getDevice(int row) {
        return familys.get(row);
    }

    @Override
    public int getViewTypeCount() {
        return 5;
    }
}
