### ISSUE TITLE
The application may be doing too much work on its main thread

### ISSUE THREAD

**Issue by buddyfavors** [InQBarna/TableFixHeaders#61]
When I'm scrolling the table view around I'm seeing considerable lag.

```
07-31 09:42:39.250      857-857/com.inqbarna.tablefixheaders.samples I/Choreographer﹕ Skipped 47 frames!  The application may be doing too much work on its main thread.
07-31 09:42:39.430      857-857/com.inqbarna.tablefixheaders.samples I/Choreographer﹕ Skipped 41 frames!  The application may be doing too much work on its main thread.
07-31 09:42:39.610      857-857/com.inqbarna.tablefixheaders.samples I/Choreographer﹕ Skipped 39 frames!  The application may be doing too much work on its main thread.
07-31 09:42:39.790      857-857/com.inqbarna.tablefixheaders.samples I/Choreographer﹕ Skipped 42 frames!  The application may be doing too much work on its main thread.
07-31 09:42:39.980      857-857/com.inqbarna.tablefixheaders.samples I/Choreographer﹕ Skipped 43 frames!  The application may be doing too much work on its main thread.
```

When using the Navigation Drawer (http://developer.android.com/design/patterns/navigation-drawer.html) and this plugin the table is unusable and locks up. When using your sample it's usable but still reports there is too much work.

**Comment by badarshahzad** [comment]
This is not related to your application it is just system information. I found this answer [here](https://teamtreehouse.com/community/ichoreographer-skipped-37-frames-the-application-may-be-doing-too-much-work-on-its-main-thread) what you say about this ? I am also looking for answer for last 3 hours. :+1:
