### ISSUE TITLE
How to make the cell textview height to wrapcontent instead of a fixed height.

### ISSUE THREAD

**Issue by noundla** [InQBarna/TableFixHeaders#70]
I would like to increase the entire row height based on the max text height. Is this already implemented? Can you please let me know how to do this with your library?
Thanks.

**Comment by BraisGabin** [comment]
Dupe #7.

**Comment by noundla** [comment]
Thanks for reply. I saw that thread before asking this question. I thought that you may have other work around for this. Anyhow, I just have implemented the work around(not bad) in Adapter class. Here is the code which I have implemented. This might be helpfull for someone. 
         
      int heights[];
      private void prepareRowHeights(){
		heights = new int[getRowCount()+1];
		TextView tv = (TextView)inflater.inflate(R.layout.text_body_cell, null);
		LayoutParams params = new LayoutParams(LayoutParams.WRAP_CONTENT, LayoutParams.WRAP_CONTENT);
		tv.setLayoutParams(params);

		//calculate the row header separately, because it will have the different style of textview
		prepareHeaderRowHeight();

		//update the body cell height
		for(int row=1;row<getRowCount()+1;row++){
			int maxHeight = 0;
			//columns including the header, so it is +1
			for(int col=0;col<getColumnCount()+1;col++){
				params.width = widths[col];
				String text = (String)table[row][col];

				if(!TextUtils.isEmpty(text)){
					//get the height of the textView based on the text that fits in.
					int height = getTextHeight(tv,text, widths[col]);
					//check whether latest height is greater than old view height in the same row
					if(maxHeight < height){
						maxHeight = height;
					}
				}
			}
			//store the maxheight value
			heights[row] = maxHeight;
		}
	}

	private void prepareHeaderRowHeight(){
		TextView tv = (TextView)inflater.inflate(R.layout.text_header_cell, null);
		LayoutParams params = new LayoutParams(LayoutParams.WRAP_CONTENT, LayoutParams.WRAP_CONTENT);
		tv.setLayoutParams(params);
		String text = (String)table[0][0];
		heights[0] = getTextHeight(tv, text, widths[0]);
	}

	private int getTextHeight(TextView textView, String text, int maxWidth) {
		textView.setText(text);
		int widthMeasureSpec = MeasureSpec.makeMeasureSpec(maxWidth-textView.getPaddingLeft()-textView.getPaddingRight(), MeasureSpec.AT_MOST);
		int heightMeasureSpec = MeasureSpec.makeMeasureSpec(0, MeasureSpec.UNSPECIFIED);
		textView.measure(widthMeasureSpec, heightMeasureSpec);
		int measuredHeight = textView.getMeasuredHeight()+textView.getPaddingTop()+textView.getPaddingBottom();
		return measuredHeight;
	}

P.S: Library is awesome. It would be helpful for us if you can provide the wiki :)
