### ISSUE TITLE
No notifyDataSetChanged() method?

### ISSUE THREAD

**Issue by zhupengGitHub** [InQBarna/TableFixHeaders#84]
There is no notifyDataSetChanged() method,when the adapter's data changed，how can I notify the table to refresh?

**Comment by ashx1** [comment]
There is a notifyDataSetChanged() method on TableAdapter: https://github.com/InQBarna/TableFixHeaders/blob/master/library/src/main/java/com/inqbarna/tablefixheaders/adapters/BaseTableAdapter.java.

**Comment by zhupengGitHub** [comment]
thank you!
