### ISSUE TITLE
Scroll on specific position when landed.

### ISSUE THREAD

**Issue by SaadBilal** [InQBarna/TableFixHeaders#85]
@BraisGabin @InQBarna 
Is there any way to land on specific location i.e can we set scroll to some X location when app first load table?

**Comment by ashx1** [comment]
Yes, you should be able to use method scrollTo(x, y).

**Comment by SaadBilal** [comment]
@ashx1  i have tried scrollTo(x,y) method but app crashes. Can you share more details?

**Comment by ashx1** [comment]
@SaadBilal What values are you passing in, what is the details of the error?

**Comment by BraisGabin** [comment]
Related with #19.

**Comment by SaadBilal** [comment]
This is working. Thank
