### ISSUE TITLE
Preload next rows for smooth scroll 

### ISSUE THREAD

**Issue by mittay** [InQBarna/TableFixHeaders#93]
Hello! I am trying to implement this lib with DB data. I have created AsynkTask in the getView() method to get data for each cell and now I have lag on fast scroll (AsynkTask not finished and I see blank cell). How can I preload 10 or more rows? Thanks

**Comment by BraisGabin** [comment]
I think that this is not a library issue. If you want to preload your data when TFH ask you for the row N you can run a AsynkTask that preload the rows N to N+9. But as I said, this is not a library issue.
