### ISSUE TITLE
 How to set up two rows can not be moved

### ISSUE THREAD

**Issue by probaby** [InQBarna/TableFixHeaders#99]
i want to set two tows  cant move,but i dont know how to set.

**Comment by BraisGabin** [comment]
Dupe #54

**Comment by probaby** [comment]
ok,thanks,
and there are other problem, when i use it inside of fragment,
**
MatrixTableAdapter<String> matrixTableAdapter = new MatrixTableAdapter<String>(this.getActivity(),str);
tableFixHeaders.setAdapter(matrixTableAdapter);
**
get activity by this.getActivity(),but there are some error
com.inqbarna.tablefixheaders.adapters.TableAdapter)' on a null object reference
please tell me why,thank you very much.
